#!/usr/bin/env lua
--[[
  generate-hyprland-conf.lua — composes ~/.config/hypr/hyprland.conf.

  Usage:
    lua generate-hyprland-conf.lua <repo_root> <theme_hypr_lua> <user_lua> [local_lua]

  Prints the finished hyprlang config to stdout. Never touches the
  filesystem itself beyond reading these inputs — the caller (apply.sh)
  decides where to write the result.
]]

local repo_root = assert(arg[1], "missing <repo_root>")
local theme_path = assert(arg[2], "missing <theme_hypr_lua>")
local user_path = assert(arg[3], "missing <user_lua>")
local local_path = arg[4] -- optional

local hypr_dir = repo_root .. "/config/hypr"
package.path = hypr_dir .. "/?.lua;" .. package.path

local function load_table(path, what)
  local chunk, err = loadfile(path)
  if not chunk then
    io.stderr:write(string.format("error loading %s (%s): %s\n", what, path, err))
    os.exit(1)
  end
  local ok, result = pcall(chunk)
  if not ok then
    io.stderr:write(string.format("error executing %s (%s): %s\n", what, path, result))
    os.exit(1)
  end
  return result
end

-- Globals consumed by the modules below. Kept as explicit globals (rather
-- than threaded through every function) so each module file stays a plain,
-- readable script.
THEME = load_table(theme_path, "theme")
USER = load_table(user_path, "user config")
LOCAL = nil
if local_path and local_path ~= "" then
  local f = io.open(local_path, "r")
  if f then
    f:close()
    LOCAL = load_table(local_path, "local override")
  end
end

local hl = require("hl")

hl.comment("Generated by cesarmanzocode-rice — do not edit by hand.")
hl.comment("Edit the Lua modules under config/hypr/, themes/<name>/hypr.lua,")
hl.comment("or ~/.config/cesarmanzocode-rice/{user,local}.lua instead, then")
hl.comment("re-run ./apply.sh")
hl.blank()

local manifest = load_table(hypr_dir .. "/hyprland.lua", "manifest")
for _, modname in ipairs(manifest) do
  dofile(hypr_dir .. "/" .. modname)
end

io.write(hl.dump())
